### PR TITLE
Home task №13

### PR DESCRIPTION
**Pull request by mykolamuntian**
Task: write a recursive procedure for displaying the digits of a natural number in the reverse order.
This application is universal and can turn any sequence of characters. If we only need to rotate numbers, I can add several input tests (to enter only numbers) and convert from strings to int. But, in general, I believe that the work of the application is quite correct.

### CODE REVIEW

**Comment by strazhkoe** [comment]
Please add one more method that reverses an integer.

**Comment by mykolamuntian** [comment]
Changes have been made according to your remarks. Check, please.

**Comment by strazhkoe** [comment]
Is it possible not to use String during the revert?

**Comment by mykolamuntian** [comment]
The task was redone without using strings

**Pull request merged**
